name: influra
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

# An extension for generating assets file located in helpers folder.
flutter_assets:
  assets_path: assets/
  output_path: lib/core/helpers/
  filename: app_images.dart
  field_prefix:

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.7
  flutter_native_splash: ^2.0.2
  # For networking.
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  # For responsivity.
  flutter_screenutil: ^5.9.0
  # For dependency injection.
  get_it: ^7.6.7




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
