import 'app_images.dart';

class AppConstants {

  static const String baseUrl = 'https://enjoyed-wahoo-divine.ngrok-free.app/';
  static const List<String> influenersImages = [
    Assets.imagesInfluencersElwakil,
    Assets.imagesInfluencersSrry,
    Assets.imagesInfluencersS7s,
    Assets.imagesInfluencersMon3sh,
    Assets.imagesInfluencersNso7i,
    Assets.imagesInfluencersMarzouqi,
  ];
  static const List<String> influenersNames = [
    'Ahmed El Wakil',
    'Marwan Serry',
    'S7S',
    'mon3esh',
    'Amr Nasohi',
    'Muhammad Marzouqi',
  ];
  static const List<String> influenersCategories = [
    'Car',
    'Football',
    'Food',
    'Food',
    'Football',
    'Car',
  ];

  static const List<String> categories = [
    'Sports',
    'Food',
    'Cars',
    'Fashion',
    'Arts',
    'Electronics',
    'Technology',
    'Science',
    'Fitness',
    'Entertainment',
    'Travel',
    'Business',
    'Education',
    'Home',
    'Automotive',
    'Relationships',
    'Parenting',
    'Self-Improvement',
    'History',
    'Politics',
    'Environment',
    'Religion',
    'Writing',
    'Music',
    'Movies',
    'Gaming',
    'Photography',
    'Pets',
    'Philosophy',
    'Psychology',
  ];
  static const List<String> categoriesImages = [
    Assets.imagesCategoriesSports,
    Assets.imagesCategoriesFood,
    Assets.imagesCategoriesCar,
    Assets.imagesCategoriesFashion,
    Assets.imagesCategoriesArts,
    Assets.imagesCategoriesElectronics,
    Assets.imagesCategoriesSports,
    Assets.imagesCategoriesFood,
    Assets.imagesCategoriesCar,
    Assets.imagesCategoriesFashion,
    Assets.imagesCategoriesArts,
    Assets.imagesCategoriesElectronics,
    Assets.imagesCategoriesSports,
    Assets.imagesCategoriesFood,
    Assets.imagesCategoriesCar,
    Assets.imagesCategoriesFashion,
    Assets.imagesCategoriesArts,
    Assets.imagesCategoriesElectronics,
    Assets.imagesCategoriesSports,
    Assets.imagesCategoriesFood,
    Assets.imagesCategoriesCar,
    Assets.imagesCategoriesFashion,
    Assets.imagesCategoriesArts,
    Assets.imagesCategoriesElectronics,
    Assets.imagesCategoriesSports,
    Assets.imagesCategoriesFood,
    Assets.imagesCategoriesCar,
    Assets.imagesCategoriesFashion,
    Assets.imagesCategoriesArts,
    Assets.imagesCategoriesElectronics,
    Assets.imagesCategoriesSports,
    Assets.imagesCategoriesFood,
    Assets.imagesCategoriesCar,
    Assets.imagesCategoriesFashion,
    Assets.imagesCategoriesArts,
    Assets.imagesCategoriesElectronics,
  ];
}
